### Test send
POST http://localhost:8000/api/send/702V_-A
content-type: application/json

{
"message": "Hello World",
  "title": "Hello World"
}


### Test send with key
POST http://localhost:8000/api/send/p9hRv77
content-type: application/json

{
    "message": "Hello World"
}

### Test send No Key
POST http://localhost:8000/api/send
content-type: application/json

{
  "key": "gkF6UU5",
  "message": "Hello World"
}

### Test send GET
GET http://localhost:8000/api/send/gkF6UU5
